CC=g++
CFLAGS=-std=c++17 -Wall -Wextra
EXEC=./tp02

$(EXEC): conjuntoDisjunto.cpp aresta.cpp grafo.cpp main.cpp
	$(CC) $(CFLAGS) conjuntoDisjunto.cpp aresta.cpp grafo.cpp main.cpp -o $(EXEC)
clean:
	rm tp02
